### ISSUE TITLE
Mellow Vape Crack contains rat

### ISSUE THREAD

**Issue by Alangopro** [RandomVapeUser/Vape-4.11#6]
![image](https://github.com/user-attachments/assets/d45ff35d-a4c6-45ae-99d8-3c70ccdbdff0)
> after huge pain in decompiling this shit, i found out that parts of the code downloads fake adobe
> program wich then grabs all your data when you login into your pc, to remove this malware
> please consider deleting this directories` C:\ProgramData\Adobe` and `C:\Users\%USERNAME%\AppData\Local\Temp`,

> **proof of the mellow malware:**

![image](https://github.com/user-attachments/assets/1edfbe24-a659-47a7-8c0a-349ff7554157)

for all, im gonna rewrite that crack so it wont contain that malware,
if someone would want the crack version without malware join my server

<a href="http://firenox.ct8.pl/discord"><img src="https://cdn.discordapp.com/icons/1089306104225349662/960ba1bff09a5ee2543ba1126162c4f2.png?size=1024&format=webp&quality=lossless&width=0&height=256" width="20" height="20"></a> server: [.gg/BRcQEhqJax](http://firenox.ct8.pl/discord) | @RandomVapeUser remove that release for safety.

**Comment by RandomVapeUser** [comment]
thank you very much Il remove it
